spring:
  application:
    name: MatchCascade
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

logging:
  level:
    org.hibernate.stat: debug
